#!/usr/bin/env python3
"""Render the human-readable VTI assessment index from authoritative submissions."""
from __future__ import annotations

from pathlib import Path
import argparse
import sys
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
PROFILE_PATH = ROOT / "profiles" / "dtg" / "vti-assessment-profile.yaml"
SUBMISSION_DIR = ROOT / "examples" / "cross-spec" / "vti-assessment"
OUTPUT_PATH = ROOT / "docs" / "vti-assessment-index.md"


def load_yaml(path: Path) -> dict[str, Any]:
    value = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(value, dict):
        raise ValueError(f"{path}: expected mapping")
    return value


def render() -> str:
    profile = load_yaml(PROFILE_PATH)
    mappings = {entry["family"]: entry for entry in profile.get("requirement_map") or []}
    submissions = []
    for path in sorted(SUBMISSION_DIR.glob("*.yaml")):
        item = load_yaml(path)
        item["_path"] = path.relative_to(ROOT).as_posix()
        submissions.append(item)

    complete = {item["family"]: item for item in submissions}

    lines = [
        "---",
        "layout: default",
        'title: "VTI assessment index"',
        "parent: Reference",
        "nav_order: 5",
        "has_toc: true",
        "---",
        "# VTI assessment index",
        "",
        "This page is generated from the authoritative RAHP VTI assessment submissions and the active VTI assessment profile. Do not edit the assessment table by hand.",
        "",
        "## Active upstream baseline",
        "",
        f"- Repository: `{profile['vti_source']['repository']}`",
        f"- Document Status: `{profile['vti_source']['document_status']}`",
        f"- Commit: `{profile['vti_source']['commit']}`",
        "",
        "## Complete assessment submissions",
        "",
        "| Assessment | Family | VTI requirements | Disposition | Evidence items | Reassessment state |",
        "|---|---|---|---|---:|---|",
    ]

    for item in sorted(submissions, key=lambda value: value["assessment_id"]):
        reqs = ", ".join(f"`{req}`" for req in item["requirements"])
        lines.append(
            f"| [`{item['assessment_id']}`](../{item['_path']}) | "
            f"{item['family']} | {reqs} | `{item['disposition']}` | "
            f"{len(item['evidence'])} | `{item['reassessment']['state']}` |"
        )

    lines += [
        "",
        "## Remaining requirement families",
        "",
        "| Family | VTI requirements | Evidence state | Assessment submission |",
        "|---|---|---|---|",
    ]

    for family, mapping in mappings.items():
        reqs = ", ".join(f"`{req}`" for req in mapping.get("requirements") or [])
        if family in complete:
            submission = complete[family]
            state = mapping.get("evidence_state", "unknown")
            submission_cell = f"`{submission['assessment_id']}`"
        else:
            state = mapping.get("evidence_state", "unknown")
            submission_cell = "not yet published"
        lines.append(f"| {family} | {reqs} | `{state}` | {submission_cell} |")

    lines += [
        "",
        "## Interpretation boundary",
        "",
        "A `supported` RAHP disposition means that the cited evidence supports the assessed property within the pinned scope and conditions. It is not a VTI conformance grant, a universal proof, or permission to infer support for adjacent requirement families.",
        "",
        "Missing, stale, contradictory, unavailable, or insufficient evidence remains `indeterminate`; it is never silently promoted to support.",
        "",
        "_Generated by `python3 tools/render_vti_assessment_index.py`._",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = render()
    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if current != expected:
            print("FAIL VTI assessment index: generated documentation is stale", file=sys.stderr)
            return 1
        print("PASS VTI assessment index")
        return 0

    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
